version: '3'

services:
  ingress:
    image: fabiocicerchia/nginx-lua
    environment:
      - NGINX_PORT=80
    volumes:
      - ./etc/ingress/templates:/etc/nginx/templates:ro
    ports:
      - 8000:80
    depends_on:
      - api-gateway
      - s3

  api-gateway:
    build: .
    environment:
      - S3_ACCESS_KEY=GAFkFniBxbMDJH7e
      - S3_SECRET_KEY=qVKkKXzLPuo3KtbGk4KOtfTBOon46caG
      - S3_FILE_PATH=/ad-auto-services/report-files/reports/1.xlsx
    ports:
      - 9010:9090
    depends_on:
      - s3

  s3:
    image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9020:9000
      - 9021:9001